image: privacybydesign/golang_sql:latest

stages:
  - build

before_script:
  - set -euxo pipefail

build:
  stage: build
  variables:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
    PACKAGE_NAME: github.com/privacybydesign/irma_server_info
    artifacts:
      # Disabling artifact expiry is not supported yet, so make
      expire_in: 100 year
      paths:
        - artifacts/*
      script:
        - mkdir -p artifacts
        - go build -a -ldflags '-extldflags "-static"' -o "artifacts/irma_server_info" .

