name: build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: go fix
        run: go fix ./...

      - name: build
        run: |
          mkdir -p artifacts
          go build -a -ldflags '-extldflags "-static"' -o artifacts/irma-server-info .
          cp db.sql artifacts/db.sql

      - uses: actions/upload-artifact@v4
        with:
          name: irma-server-info
          path: artifacts/
          retention-days: 90
